### ISSUE TITLE
HSIC formulation

### ISSUE THREAD

**Issue by ylee0716** [xiao-he/HSIC#1]
Hello, I have read your code about HSIC, thanks for your help! But I found the formulation about HSIC is HSIC=(m-1)^(-2)tr(HKHL) in original paper, and your code use np.sum(KHLH) rather than np.trace(HKHL). I want to know why you write that. Looking forword to your reply!

**Comment by xiao-he** [comment]
Hi, tr(KL) = np.sum(K.*L). In the code it is element wise multiplication.

**Comment by xiao-he** [comment]
And the reason is that np.sum() seems to be a bit faster.

**Comment by ylee0716** [comment]
Thank you very much！
